### ISSUE TITLE
Invalid Ethereum wallet address displayed in app

### ISSUE THREAD

**Issue by kapoorsaumitra** [metafy-social/eth-unwrapped#11]
**Description:**
I noticed that the app is displaying an 'invalid address' for an Ethereum wallet addresses. 

**Expected behavior:**
The app should display a valid and accurate Ethereum wallet address "unwrapped" 

**Actual behavior:**
The app is showing an invalid Ethereum wallet address and does not display the "unwrapped"

**Screenshot**
![image](https://github.com/metafy-social/eth-unwrapped/assets/68214324/96edaeea-065f-4ee6-8a15-c2a5647bf2ea)

**Comment by advaita-saha** [comment]
Hey sorry for this issue.
Somehow the backend server is down. Our team is working on it
We have checked and there is no error, if you run the app locally
