### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by dhrumishah** [metafy-social/eth-unwrapped#13]
The website is not responsive. I would like to work on it.

![image](https://github.com/metafy-social/eth-unwrapped/assets/84569241/047a78bd-7817-45fb-bba1-606e4cdfb1fe)

**Comment by shahkushal38** [comment]
Hii, @dhrumishah can you create a figma design for the app and based on that we can discuss and assign the issue to you.

**Comment by dhrumishah** [comment]
> Hii, @dhrumishah can you create a figma design for the app and based on that we can discuss and assign the issue to you.

Hey! I don't know how to edit figma files, but the design will be same just the things will me more aligned in small screens. Nothing to change in the design. 

If you say, I'll first make it responsive , share the screenshot with you here and then I will make a PR.

**Comment by advaita-saha** [comment]
You can see that the frontend part is kept as a submodule in a different repo
We are not taking contributions in UI fixes
