### ISSUE TITLE
The footer section is not initially visible and can only be accessed by scrolling down the page.

### ISSUE THREAD

**Issue by abhijeetnishal** [metafy-social/eth-unwrapped#14]
**Describe the bug**
The footer section, which typically contains important information such as contact details, links to additional pages, copyright notices, and navigation links, is not visible to users when they initially load the webpage. In order to access the footer, users have to scroll down the page, which creates an inconvenience and hampers the overall user experience. Search engine crawlers rely on visible content to determine the relevance and ranking of a webpage.

**To Reproduce**
1. Go to Landing page
2. Scroll down page
3. See error

**Expected behavior**
It is recommended to ensure that the footer section is visible by default, without requiring users to scroll down. This can be achieved by adjusting the page layout or implementing a sticky footer that remains visible at all times, regardless of the user's position on the page. By making the footer easily accessible, the website will enhance its usability, improve accessibility, and provide a more satisfactory user experience.

**Screenshots**
<img width="1439" alt="Screenshot 2023-05-22 at 1 10 25 PM" src="https://github.com/metafy-social/eth-unwrapped/assets/83833440/07c34db2-59c0-4d9b-a292-182ddbfcdd14">

**Comment by abhijeetnishal** [comment]
Please assign me this issue under GSSOC2023

**Comment by advaita-saha** [comment]
You can see that the frontend part is kept as a submodule in a different repo
We are not taking contributions in UI fixes
