### ISSUE TITLE
Missing Documentation Template Issue in Repository

### ISSUE THREAD

**Issue by Nishitbaria** [metafy-social/eth-unwrapped#22]
`Documentation Template: ` This template facilitates the creation of comprehensive documentation by providing a structured format, including sections for an introduction, usage instructions, examples, and other relevant details.

**Comment by shahkushal38** [comment]
can you describe on the task you want to perform for Documentation Template, based on that we shall assign it to you

**Comment by Nishitbaria** [comment]
I will create a template that will assist contributors who are interested in creating specific issues in the documentation, so they can use this template.
