### ISSUE TITLE
add new look to the readme 

### ISSUE THREAD

**Issue by Ayush-Tibrewal** [metafy-social/eth-unwrapped#4]
### Is your feature request related to a problem? Please describe
I have given your README a completely new look and added simplified text that is highly useful for new contributors. I incorporated the text you provided and made sure it enhances the overall appeal of the document. Please review my changes and let me know if there are any issues. If you have any concerns, feel free to assign me to the relevant issue, and I will address it as soon as possible.

**Comment by Ayush-Tibrewal** [comment]
@advaita-saha please assign me with the issue

**Comment by advaita-saha** [comment]
Go ahead
