### ISSUE TITLE
[bug] Address bar 

### ISSUE THREAD

**Issue by Ghat0tkach** [metafy-social/eth-unwrapped#5]
**Describe the bug**
The addresss value gets stored on the current address bar of website
**To Reproduce**
![image](https://github.com/metafy-social/eth-unwrapped/assets/59855919/22a67142-1a33-4b52-acb2-931118f56498)

This could be fixed modifying the Getyourwrapped by prevent default function

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bartick** [comment]
Yes, that's correct. The backend is currently down, which means we've lost connection to the server. However, the address bar should start working again once we rehost the backend. So there's no need to worry @Ghat0tkach
