### ISSUE TITLE
Landing page tutorial 

### ISSUE THREAD

**Issue by shivam-jainn** [metafy-social/eth-unwrapped#6]
I am new to blockchain . Infact consider me as a noob . So as someone who has  0 experience  on blockchain or anything . It would be great to include a tutorial on how to get addresses  when the user visits the page for first time .

It will prolly be modal with 5 most common wallets . And once user click on it , we can have a gif/slideshow of steps guiding them on how to do the necessary

**Comment by advaita-saha** [comment]
not needed
