### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by Rupantar-Borphukan** [metafy-social/eth-unwrapped#9]
The current background is nothing but given a dot type style. We can run a vedio or animation using D3js (3D animation) using Web3js .

![ETH background add](https://github.com/metafy-social/eth-unwrapped/assets/94108574/8a00e53a-de3e-4259-8737-7ddb85d0e4dc)

We can make hover effect or Glassmorphism or claymorphism of this section (where I have round using green pen) and much more can be added or design. 

Assign me to solve that problem and fix this under GSSoC '23 Contributor.

**Comment by advaita-saha** [comment]
not needed
